"use client";

import { useCallback, useEffect, useState } from "react";

/**
 * Loads the real FrankenSim numerical kernels (compiled to WASM) in a SINGLE
 * shared Web Worker and exposes `call(fn, ...args)`.
 *
 * The worker + wasm live in /public/fs-wasm (generated by `wasm-bindgen` from the
 * `fs-wasm` crate in ~/projects/frankensim). Every result is the actual compiled
 * Rust computation — no mocks. The worker is a module-level singleton so a page
 * with ten demos shares one wasm instance instead of spawning ten.
 *
 * Exported kernels (all args numbers; Float64Array or number results):
 *  poisson2d(n) · heat_frames(n,frames,spf) · orr_sommerfeld_max_growth(re,a,n) ·
 *  orr_sommerfeld_curve(a,n,reMin,reMax,steps) · chebyshev_fit(kind,samples) ·
 *  chebyshev_spectrum(kind) · taylor_bound(center,radius,order) ·
 *  autodiff_derivatives(xmin,xmax,samples) · finite_difference_error(x0,steps) ·
 *  randomized_svd(n,rank,seed) · fft_power_spectrum(n,seed) ·
 *  laplacian_modes(n,k) · qmc_vs_mc(maxLog2,seed) · robust_hull(radius) ·
 *  compensated_sum(count,log10big) · engine()
 */
type Resolver = { resolve: (v: unknown) => void; reject: (e: Error) => void };

let worker: Worker | null = null;
let engineStr = "";
let ready = false;
const pending = new Map<number, Resolver>();
const readySubs = new Set<(engine: string) => void>();
let idCounter = 0;

function ensureWorker(): Worker | null {
  if (worker) return worker;
  if (typeof Worker === "undefined") return null;
  try {
    worker = new Worker("/fs-wasm/worker.js", { type: "module" });
  } catch {
    return null;
  }
  worker.onmessage = (ev: MessageEvent) => {
    const d = ev.data;
    if (d?.type === "ready") {
      engineStr = d.engine ?? "";
      ready = true;
      readySubs.forEach((f) => f(engineStr));
      return;
    }
    const p = pending.get(d.id);
    if (!p) return;
    pending.delete(d.id);
    if (d.ok) p.resolve(d.result);
    else p.reject(new Error(d.error || "wasm error"));
  };
  worker.onerror = () => {
    pending.forEach((p) => p.reject(new Error("worker error")));
    pending.clear();
  };
  return worker;
}

export function useFsWasm() {
  const [isReady, setReady] = useState(ready);
  const [engine, setEngine] = useState(engineStr);

  useEffect(() => {
    ensureWorker();
    if (ready) {
      setReady(true);
      setEngine(engineStr);
      return;
    }
    const sub = (e: string) => {
      setReady(true);
      setEngine(e);
    };
    readySubs.add(sub);
    return () => {
      readySubs.delete(sub);
    };
  }, []);

  const call = useCallback(<T = Float64Array>(fn: string, ...args: number[]): Promise<T> => {
    return new Promise<T>((resolve, reject) => {
      const w = ensureWorker();
      if (!w) {
        reject(new Error("wasm worker unavailable"));
        return;
      }
      const id = ++idCounter;
      pending.set(id, { resolve: resolve as (v: unknown) => void, reject });
      w.postMessage({ id, fn, args });
    });
  }, []);

  return { ready: isReady, engine, call };
}
